config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :tools do
    resources :bookings, only: [:new, :create, :edit, :update]
  end
  resources :bookings, only: [:index, :show, :edit, :update, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :tool

  def price_total
    (end_date - start_date).to_i * tool.price
  end
end

app/models/tool.rb
class Tool < ApplicationRecord
  CATEGORIES = ["Tents", "Footwear", "Sleeping bags", "Accessoires", "Backpacks", "Clothing"]
  has_many_attached :photos
  has_many :bookings, dependent: :destroy
  belongs_to :user

  validates :category, inclusion: { in: CATEGORIES }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tools
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit

  before_action :configure_permitted_parameters, if: :devise_controller?

  # Pundit: white-list approach.
  # after_action :verify_authorized, except: :index, unless: :skip_pundit?
  # after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[ show edit update destroy ]

  def index
    @bookings = policy_scope(Booking)
    authorize @bookings
  end

  def show
    authorize @booking
  end

  # GET /bookings/new
  def new
    @tool = Tool.find(params[:tool_id])
    @booking = Booking.new
  end

  # POST /bookings
  def create
    @tool = Tool.find(params[:tool_id])
    @booking = Booking.new(booking_params)
    @booking.tool = @tool
    @booking.user = current_user
    @booking.save
    redirect_to bookings_path
  end

   # GET /bookings/1/edit
   def edit
   end

  # PATCH/PUT /bookings/1
  def update
      if @booking.update(booking_params)
        redirect_to booking_path(@booking), notice: "Booking was successfully updated."
      else
        render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /bookings/1
  def destroy
    @booking.destroy

    respond_to do |format|
      format.html { redirect_to bookings_url, notice: "Booking was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def booking_params
      params.require(:booking).permit(:start_date, :end_date)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :show ]

  def index
    if params[:query].present?
      @tools = policy_scope(Tool).where("category ILIKE ?", "%#{params[:query]}%")
    elsif params[:category].present?
        @tools = policy_scope(Tool).where(category: params[:category])
    else
      @tools = policy_scope(Tool).all
    end
  end

  def show
    @tool = Tool.find(params[:id])
    authorize @tool
  end

  def new
    @tool = Tool.new
    authorize @tool
  end

  def edit
    @tool = Tool.find(params[:id])
    authorize @tool
  end

  def create
    @tool = Tool.new(tool_params)
    @tool.user = current_user
    if @tool.save
      redirect_to tool_path(@tool)
    else
      render :new
    end
  end

  def update
    @tool = Tool.find(params[:id])
    if @tool.update(tool_params)
      redirect_to tool_url(@tool), notice: "Tool was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
    authorize @tool
  end

  def destroy
    @tool = Tool.find(params[:id])
    @tool.destroy
    redirect_to tools_url, notice: "Tool was successfully destroyed."
    authorize @tool
  end

  private

  def tool_params
    params.require(:tool).permit(:name, :category, :description, :price, photos: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<p>Equipment: <%= tool.name %></p>
<p>Price: <%= tool.price %>CHF per day</p>

<div class="d-flex align-items-center">

  <%= simple_form_for [tool, booking] do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="d-flex align-items-center">
      <% if tool.photos.any? %>
        <%= cl_image_tag tool.photos[0].key, height: 200, :crop => :fill %>
      <%end%>

      <div class="form-inputs m-3">
        <%= f.input :start_date %>
        <%= f.input :end_date %>
      </div>
    </div>

    <div>
      <%= f.button :submit, 'Confirm', class: "btn btn-primary my-3" %>
    </div>
  <% end %>
</div>

app/views/bookings/edit.html.erb
<div style="background-image: linear-gradient(rgba(255,255,255,0.2), rgba(255,255,255,0.2)),url(https://www.galeria-reisen.de/magazin/wp-content/uploads/2021/01/KanadaAdobeStock_295448049.jpeg);">
  <div class="container">
    <div class="p-4 bg-white">
      <h1>Editing rental</h1>

      <%= render 'form', booking: @booking, tool: @booking.tool %>

      <%= link_to 'Show', @booking, class:"btn btn-outline-dark" %>
      <%= link_to 'Back to my rentals', bookings_path, class:"btn btn-outline-dark" %>
    </div>
  </div>
</div>

app/views/bookings/index.html.erb
<div style="background-image: linear-gradient(rgba(255,255,255,0.2), rgba(255,255,255,0.2)),url(https://www.galeria-reisen.de/magazin/wp-content/uploads/2021/01/KanadaAdobeStock_295448049.jpeg);">
  <div class="container">
    <div class="p-4 bg-white">
      <p id="notice"><%= notice %></p>

      <h1>My rentals</h1>

      <table class="table align-middle">
        <thead>
          <tr>
            <th>Start date</th>
            <th>End date</th>
            <th>Equipment</th>
            <th>Total price</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% if policy(@bookings).index? %>
            <% @bookings.each do |booking| %>
              <tr>
                <td><%= booking.start_date %></td>
                <td><%= booking.end_date %></td>
                <td><%= booking.tool.name %></td>
                <td><%= booking.price_total %> CHF</td>
                <td><%= link_to 'Show', booking, class: "btn btn-primary" %></td>
                <td><%= link_to 'Edit', edit_booking_path(booking), class: "btn btn-primary" %></td>
                <td><%= link_to 'Delete', booking, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-primary" %></td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>

      <%= link_to 'Go to equipment', tools_path, class:"btn btn-outline-dark" %>

    </div>
  </div>
</div>

app/views/bookings/new.html.erb
<div style="background-image: linear-gradient(rgba(255,255,255,0.2), rgba(255,255,255,0.2)),url(https://www.galeria-reisen.de/magazin/wp-content/uploads/2021/01/KanadaAdobeStock_295448049.jpeg);">
  <div class="container">
    <div class=" p-4 bg-white">
      <h1>New rental</h1>

      <div>
        <%= render 'form', booking: @booking, tool: @tool %>
      </div>

      <%= link_to 'Back', tool_path(@tool), class:"btn btn-outline-dark" %>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<div style="background-image: linear-gradient(rgba(255,255,255,0.2), rgba(255,255,255,0.2)),url(https://www.galeria-reisen.de/magazin/wp-content/uploads/2021/01/KanadaAdobeStock_295448049.jpeg);">
  <div class="container">
    <div class="p-4 bg-white">
      <p id="notice"><%= notice %></p>
      <h1>My rental</h1>

      <p>
        <strong>Start date:</strong>
        <%= @booking.start_date %>
      </p>

      <p>
        <strong>End date:</strong>
        <%= @booking.end_date %>
      </p>

      <p>
        <strong>Equipment:</strong>
        <%= @booking.tool.name %>
      </p>

      <p>
        <strong>Total price:</strong>
        CHF<%= @booking.price_total %>
      </p>

      <%= link_to 'Edit', edit_booking_path(@booking), class:"btn btn-outline-dark" %>
      <%= link_to 'Back to my rentals', bookings_path, class:"btn btn-outline-dark" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rent4hike</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="bg-white">
  <div class="banner border-bottom" style="background-image: url(https://www.galeria-reisen.de/magazin/wp-content/uploads/2021/01/KanadaAdobeStock_295448049.jpeg);">
  <div class="container">
    <h1>Welcome to Rent 4 Hike!</h1>
    <p>Do you love to go hiking? Then you are in the right place!</p>
    <p>Look through all the available equipment and rent it for as long as you need</p>
    <%= link_to "Check out our equipment", tools_path, class: "btn btn-ghost" %>
    </div>
  </div>

  <div class="row g-2">

      <div class="col-lg-4 col-md-6 col-xs-8">
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://outdooradventurestore.ie/blog/wp-content/uploads/2021/02/leki.png)">
          <%= link_to "Accessoires", tools_path(category: "Accessoires") %>
        </div>
      </div>

    <div class="col-lg-4 col-md-6 col-xs-8">
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://www.roadaffair.com/wp-content/uploads/2019/06/man-hiking-backpack-shutterstock_644176402-1024x683.jpg)">
        <%= link_to "Backpacks", tools_path(category: "Backpacks") %>
      </div>
    </div>

    <div class="col-lg-4 col-md-6 col-xs-8">
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://www.salomon.com/sites/default/files/articles/images/How-to-choose-hiking-jacket-man.jpg?fit=cover&orientation=1&quality=95&optimize=high&format=pjpg&auto=webp&dpr=1)">
        <%= link_to "Clothing", tools_path(category: "Clothing") %>
      </div>
    </div>

    <div class="col-lg-4 col-md-6 col-xs-8">
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://wildlandtrekking.com/content/uploads/2020/09/Best-Low-Top-Hiking-Shoes.jpg)">
        <%= link_to "Footwear", tools_path(category: "Footwear") %>
      </div>
    </div>

    <div class="col-lg-4 col-md-6 col-xs-8">
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://www.thermarest.com/blog/wp-content/uploads/2019/04/Sleeping-Bag-Temperature-Ratings-Ben-Matthews-1600x1000-1.jpg)">
        <%= link_to "Sleeping bags", tools_path(category: "Sleeping bags") %>
      </div>
    </div>

    <div class="col-lg-4 col-md-6 col-xs-8">
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://cld.accentuate.io/245976039597/1645516544069/TELOS-ULTRALIGHT--FREESTANDING.jpg?v=0&options=w_1440)">
        <%= link_to "Tents", tools_path(category: "Tents") %>
      </div>
    </div>

</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
  <p>2022 Rent 4 Hike</p>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "My rentals", bookings_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://st4.depositphotos.com/5045705/19653/v/450/depositphotos_196539098-stock-illustration-cute-cartoon-marmot-looking-hole.jpg", class: "avatar dropdown-toggle border", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/tools/edit.html.erb
<div style="background-image: linear-gradient(rgba(255,255,255,0.2), rgba(255,255,255,0.2)),url(https://www.galeria-reisen.de/magazin/wp-content/uploads/2021/01/KanadaAdobeStock_295448049.jpeg);">
  <div class="container">
    <div class="row">
      <div class="col-sm-6 offset-3 p-4 bg-white rounded my-3">

        <h3 class="my-2"> Edit equipment</h3>
          <%= simple_form_for [ @tool ] do |f| %>
            <%= f.input :name %>
            <%= f.input :category %>
            <%= f.input :description %>
            <%= f.input :price %>
            <%= f.input :photo, as: :file %>
            <%= f.submit "Save changes", class: "btn btn-primary" %>
          <% end %>
        <div class="my-3">
          <%= link_to "Back to equipment", tools_path, class: "btn btn-ghost" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tools/index.html.erb
<div style="background-image: linear-gradient(rgba(255,255,255,0.2), rgba(255,255,255,0.2)),url(https://www.galeria-reisen.de/magazin/wp-content/uploads/2021/01/KanadaAdobeStock_295448049.jpeg);">
  <div class="container bg-white">
    <br>
    <h2 class="text-center fw-bold">Check our equipment</h2>
    <div class="d-flex align-items-center justify-content-between m-3">
      <%= form_tag tools_path, method: :get do %>
        <%= select_tag "category", options_for_select(
          ["Accessoires", "Backpacks", "Clothing", "Footwear", "Sleeping bags", "Tents"], params[:category]),
          class:"select2" %>
          <%= submit_tag "Search", class: "btn btn-primary btn-sm mx-2" %>
        <% end %>

      <div>
        <% if policy(Tool).create? %>
          <%= link_to "Add equipment", new_tool_path, class: "btn-ghost link" %>
        <% end %>
      </div>
    </div>
    <div class="row g-4 mx-2">
      <% @tools.each do |tool|%>
        <div class="col-lg-4 col-md-6 col-xs-8">
          <div class="card-trip">
            <% if tool.photos.any? %>
              <%= cl_image_tag tool.photos[0].key %>
            <%end%>

            <%= link_to tool_path(tool), class:"text-decoration-none link" do %>
              <div class="card-trip-infos">
                <div>
                  <h2><%=tool.name.capitalize %></h2>
                  <p><%= tool.description %></p>
                </div>
              <h2 class="card-trip-pricing">CHF <%= tool.price%></h2>
              </div>
            <% end %>
          </div>
        </div>
      <%end%>
    </div>
    <br>
    <br>
  </div>
</div>

app/views/tools/new.html.erb
<div style="background-image: linear-gradient(rgba(255,255,255,0.2), rgba(255,255,255,0.2)),url(https://www.galeria-reisen.de/magazin/wp-content/uploads/2021/01/KanadaAdobeStock_295448049.jpeg);">
  <div class="container">
    <div class="row">
      <div class="col-sm-6 offset-3 p-4 bg-white rounded my-3">
        <h3 class="my-2"> Add new equipment</h3>
        <%= simple_form_for [ @tool ] do |f| %>
          <%= f.input :name %>
          <%= f.input :category, collection: ["Accessoires", "Backpacks", "Clothing", "Footwear", "Sleeping bags", "Tents"]%>
          <%= f.input :description %>
          <%= f.input :price %>
          <%= f.input :photos, as: :file, input_html: { multiple: true } %>
          <%= f.submit "Add equipment", class: "btn btn-primary" %>
        <% end %>
        <div class="my-3">
          <%= link_to "Back to equipment", tools_path, class: "link" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tools/show.html.erb
<div style="background-image: linear-gradient(rgba(255,255,255,0.2), rgba(255,255,255,0.2)),url(https://www.galeria-reisen.de/magazin/wp-content/uploads/2021/01/KanadaAdobeStock_295448049.jpeg);">
  <div class="card-product container">

      <div class="d-flex justify-content-evenly align-items-center image-container">

        <% if @tool.photos.any? %>
          <% if @tool.photos.length == 1 %>
            <%= cl_image_tag @tool.photos[0].key, class: "big-image-full" %>
          <% else %>

          <%= cl_image_tag @tool.photos[0].key, class: "big-image" %>

            <div class="d-flex flex-wrap justify-content-evenly flex-grow-1 align-items-center">
              <% if @tool.photos.length >= 4 %>
                <% @tool.photos[1..4].each do |photo| %>
                  <%= cl_image_tag photo.key, class: "small-image" %>
                <% end %>
              <% elsif @tool.photos.length == 3 %>
                <% @tool.photos[1..2].each do |photo| %>
                  <%= cl_image_tag photo.key, class: "small-2" %>
                <% end %>
              <% elsif @tool.photos.length == 2 %>
                <%= cl_image_tag @tool.photos[1].key, class: "big-image" %>
              <% end %>
            </div>
          <% end %>
        <%end%>

        <div class="infos-card">
          <div class="mb-2">
            <h2><%= @tool.name.capitalize %></h2>
          </div>
            <p class="description mb-4"><%= @tool.description %></p>
            <p id="price">Price: <%= @tool.price %>CHF / day</p>
            <p>Owner: <%= @tool.user.email %></p>
            <%= link_to "Rent it", new_tool_booking_path(@tool), class: "btn btn-primary my-3"%>
        </div>
      </div>

      <div class="d-flex justify-content-between align-items-center my-5 width-100">

        <div>
          <% if policy(@tool).edit? %>
            <%= link_to 'Edit', edit_tool_path(@tool), class:"btn btn-outline-dark" %>
          <% end %>
          <% if policy(@tool).destroy? %>
            <%= link_to 'Delete', @tool, class:"btn btn-outline-dark", method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </div>

        <div>
        <%= link_to "Back to equipment", tools_path, class: "btn btn-outline-dark my-3"%>
        </div>

      </div>

  </div>

</div>